name: Lint

on:
  pull_request:

jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: 🚀 Run yamllint
        uses: reviewdog/action-yamllint@e02a49fdf53f51ddd8dfa89b09aa975043aeba38 # v1.23.0
        with:
          yamllint_flags: "projects.yaml"
          reporter: github-pr-review
          filter_mode: nofilter
          fail_level: error
          github_token: ${{ secrets.GITHUB_TOKEN }}
