name: Lint

on:
  pull_request:

jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code
        uses: actions/checkout@v3
      - name: 🚀 Run yamllint
        uses: frenck/action-yamllint@v1
